//
//  Url.swift
//  xiaofanzhuo
//
//  Created by 宋志明 on 15-1-20.
//  Copyright (c) 2015年 songzm. All rights reserved.
//

import Foundation


let BASE_URL : String = "http://api.xfz.cn/"
//let BASE_URL : String = "http://littletable.selcome.com/"
let LOGIN : String = "login"
let SET_USER_INFO : String = "users/user/setUserInfo"
let GET_TOPICLIST : String = "users/topic/getTopicList"
let GET_TOPICINFO : String = "users/topic/getTopicInfo"
let GET_USER_INFO_OPTIONS : String = "getUserInfoOptions"
let GET_ARTICLELIST : String = "users/article/getArticleList"
let GET_ACTIVITYLIST : String = "users/activity/getActivityList"
let RECOMMEND_PROJECT : String = "users/persional/RecommendProject"
let GET_RECOMMENDCODELIST : String = "users/persional/getRecommendCodeList"
let GENERATERECOMMENDCODE : String = "users/persional/generateRecommendCode"
let GETTASKINFO : String = "users/task/getTaskInfo"
let GET_TOPIC_COMMENT : String = "users/topic/getTopicComment"
let GETTASKLIST : String = "users/task/getTaskList"
let COMMENT_TO_TOPIC_REPLY : String = "users/topic/commentToTopicReply"
let TASKPUBLISHED : String = "users/persional/taskPublished"
let TASKREPLIED : String = "users/persional/taskReplied"
let SIGNUP : String = "users/activity/signUp"
let NEW_TOPIC : String = "users/topic/createNewTopic"
let UPLOAD_IMAGE : String = "uploadImage"
let PUBLISHTASK : String = "users/task/publishTask"
let SENDBOOK : String = "users/persional/bookInfo"
let CHECKINTEGRAL : String = "users/persional/checkIntegral"
let SENDBOOKINFO : String = "users/persional/sendBookInfo"
let SEND_GIFT_INFO = "users/persional/sendGiftInfo"
let OFFERHELP : String = "users/task/offerHelp"
let DONETASK : String = "users/task/doneTask"
let CANCELTASK : String = "users/task/cancelTask"
let REPLY_TO_TOPIC : String = "users/topic/replyToTopic"
let TOPIC_REPLYED : String = "users/persional/topicReplied"
let TOPIC_PUBLISHED : String =  "users/persional/topicPublished"
let GETUSERINFO : String = "users/user/getUserInfo"
let SEARCH : String = "search"
let PRAISE_TO_TOPLY_REPLY : String = "users/topic/praiseToTopicReply"
let CANCEL_PRAISE_TO_TOPIC_REPLY : String = "users/topic/cancelPraiseToTopicReply"
let EDIT_TOPIC_REPLY : String = "users/topic/editTopicReply"
let DEL_TOPIC_REPLY : String =  "users/topic/delTopicReply"
let GETINTEGRAL : String = "users/user/getIntegral"
let EDITTASK : String = "users/task/editTask"
let DEL_TOPIC_REPLY_COMMENT : String = "users/topic/delTopicReplyComment"
let EDIT_TOPIC : String = "users/topic/editTopic"
let UPDATE_USERINFO : String = "users/user/updateUserInfo"
let BLOCK_TO_TOPIC_REPLY_COMMENT : String =  "users/topic/blockToTopicReplyComment"
let BLOCK_TO_TOPIC_REPLY : String = "users/topic/blockToTopicReply"
let GETARTICLEINFO : String = "users/article/getArticleInfo"
let GETACTIVITYINFO : String = "users/activity/getActivityInfo"
let GETMESSAGELIST : String = "users/message/getMessageList"
let BINDACCOUNT : String = "users/user/bindAccount"
let RELEASEBIND : String = "users/user/releaseBind"
let BLOCK_TO_TOPIC : String =  "users/topic/blockToTopic"
let GET_USER_STATE : String = "getUserState"
let GIFT_LIST : String = "users/persional/giftList"
let GIFT_INFO = "users/persional/giftInfo"
let ADD_COLLECTION : String = "users/topic/addCollection"
let GET_COLLECTION : String = "users/topic/getCollection"
let CANCEL_COLLECTION : String = "users/topic/cancelCollection"
let LOGIN_NEW : String = "loginNew"
let REGISTER_NEW : String = "registerNew"
let GET_AUTH_CODE : String = "getAuthCode"
let GETARTICLELIST_BYLABELLED = "users/article/getArticleListByLabelId"
let GETACTIVITYLIST_BYLABELLED = "users/activity/getActivityListByLabelId"
let MY_TOPIC_REPLY_LIST = "users/persional/myTopicReplyList"
let FORGET_PASSWORD = "forgetPass"
let UPDATE_PASSWORD = "users/user/updatePass"
let GET_FRONT_PAGE = "getFrontPage"
let VALIDATE_PHONE = "validatePhone"
let VALIDATE_CAPTCHA = "valideteCaptcha"
let RESET_PASS = "resetPass"
let GET_PUSH_COUNT = "users/push/getPushCount"
let CLEAR_PUSH_COUNT = "users/push/clearPushCount"
let DELETE_TASK_REPLY = "users/task/deleteTaskReply"
let GET_ACTIVITY_REPLYS = "users/activity/getActivityReplys"
let REPLY_TO_ACTIVITY = "users/activity/replyToActivity"
let DELETE_ACTIVITY_REPLY = "users/activity/deleteActivityReply"
let GET_ARTICLE_REPLYS = "users/article/getArticleReplys"
let REPLY_TO_ARTICLE = "users/article/replyToArticle"
let DELETE_ARTICLE_REPLY = "users/article/deleteArticleReply"
let SEARCH_USER_BY_USERNAME = "users/searchUserByUserName"
let INVITE = "users/invite"


